[package]
name = "rust_sapper"
version = "0.1.0"
authors = ["siphilia <siphilia.rn@gmail.com>"]

[dependencies]
sapper = { git = "https://github.com/sappworks/sapper" }
log = "0.3"
env_logger = "0.3"
